spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        userRandomPolicy: true
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/