spring:
  application:
    name: "analyzer"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Логирование и форматирование SQL
    show-sql: true  # Показывать SQL, лучше отключить в продакшене

  data:
    jdbc:
      dialect: postgresql

  datasource: # Параметры подключения к базе данных
    url: "jdbc:postgresql://localhost:6541/plusSmartHomeTech"
    username: plusSmartHomeTech
    password: plusSmartHomeTech
    driver-class-name: org.postgresql.Driver

  sql:
    init: # Инициализация схемы SQL
      schema-locations: schema.sql

grpc: # Параметры gRPC клиента
  client:
    hub-router:
      address: "static://localhost:59090"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer: # Настройки анализатора
  kafka:
    topics:
      sensors-snapshot: telemetry.snapshots.v1
      sensors-events: telemetry.sensors.v1
      hubs-events: telemetry.hubs.v1

    consumer-properties:
      "bootstrap.servers": localhost:9092
      "group.id": aggregator-group
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.SensorEventDeserializer